### ISSUE TITLE
The indexer write only the first 513 rounds in dev mode.

### ISSUE THREAD

**Issue by ma-spadafora** [algorand/sandbox#104]
### The indexer write only the first 513 rounds in dev mode. 

When launched in dev mode, the indexer stops the synchronization with algod after 513 rounds.

### Environment

* Software version: 3.3.137611.dev
* Node status:
  * Last committed block: 742
  * Time since last block: 53.1s
  * Sync Time: 0.0s
  * Last consensus protocol: future
  * Next consensus protocol: future
  * Round for next consensus protocol: 743
  * Next consensus protocol supported: true
  * Last Catchpoint: 
  * Genesis ID: sandnet-v1
  * Genesis hash: yvolBA1KcmMsdHI1DZDwzfe1fH9AXW9xoxBOWbuSU20=
* Operating System: macOS  Monterey 12.2.1

### Steps to reproduce

1. Install a new sandbox in dev mode:
````
./sandbox clean
./sandbox up dev -v
````
2. Run a large number of transactions

### Expected behavior
The `indexer_db` is updated as transactions are committed.

### Actual behavior
The `indexer_db` is no longer updated after round 513 (see `blocks_header` table)

**Comment by winder** [comment]
I think you are a victim of latency in our release process. It's possible that the dev branch for indexer and algod were incompatible at the time because we were in the middle of releasing the state-proof feature.

There is another release happening soon, so I think indexer and algod are still incompatible. That should be resolved soon.

Since it is now released, you can test the state proof changes with `./sandbox up stable -v`.
