### ISSUE TITLE
Docker setup on Windows 10

### ISSUE THREAD

**Issue by galimba39** [algorand/sandbox#115]
### Subject of the issue

I experienced an issue while using the docker sandbox with Windows10, together with Git bash.

Issue error on the git bash console:
"the input device is not a TTY. If you are using mintty, try prefixing the command with 'winpty'."

### Your environment

OS:
Edition	Windows 10 Pro
Version	21H2
Installed on	‎12/‎25/‎2020
OS build	19044.1645
Experience	Windows Feature Experience Pack 120.2212.4170.0

Git:
Git for Windows 2.36.0.windows.1 (64-bit)

Docker:
Docker Desktop 4.7.1 (77678)

### Steps to reproduce

Following the guide in the git
1. In the sandbox folder
2. ./sandbox up -v

### Expected behaviour
Not showing the error message

### Actual behaviour
Showing the error message:
"the input device is not a TTY. If you are using mintty, try prefixing the command with 'winpty'."

**Comment by galimba39** [comment]
Solved using Option1: Using WSL 2

**Comment by robdmoore** [comment]
Another option is using https://github.com/MakerXStudio/algorand-sandbox-dev :)

**Comment by winder** [comment]
It sounds like a solution is in the documentation. Closing.

**Comment by fabrice102** [comment]
@winder I think the solution of using WSL 2 is more a workaround.

The option https://github.com/algorand/sandbox#option-2-using-git-for-windows-msys-2 (which is an official install option) does not seem to work.
I've tested on Win 11 21H2 and got the issue.

Replacing `dc` by `dc_pty` on these lines:
* https://github.com/algorand/sandbox/blob/46c256f527be5fc6418044a355dd51a5fd22eee8/sandbox#L259
* https://github.com/algorand/sandbox/blob/46c256f527be5fc6418044a355dd51a5fd22eee8/sandbox#L263
* https://github.com/algorand/sandbox/blob/46c256f527be5fc6418044a355dd51a5fd22eee8/sandbox#L208
solves this specific issue.

However, you then hit a similar issue with the indexer.
Since `winpty` does not work very well with pipes / `$(...)`.
You get `stdout is not a tty`.

This still seems to roughly work.

**Comment by winder** [comment]
> @winder I think the solution of using WSL 2 is more a workaround.
> 
> The option https://github.com/algorand/sandbox#option-2-using-git-for-windows-msys-2 (which is an official install option) does not seem to work.
> I've tested on Win 11 21H2 and got the issue.
> 
> Replacing `dc` by `dc_pty` on these lines:
> * https://github.com/algorand/sandbox/blob/46c256f527be5fc6418044a355dd51a5fd22eee8/sandbox#L259
> * https://github.com/algorand/sandbox/blob/46c256f527be5fc6418044a355dd51a5fd22eee8/sandbox#L263
> * https://github.com/algorand/sandbox/blob/46c256f527be5fc6418044a355dd51a5fd22eee8/sandbox#L208
> solves this specific issue.
> 
> However, you then hit a similar issue with the indexer.
> Since `winpty` does not work very well with pipes / `$(...)`.
> You get `stdout is not a tty`.
> 
> This still seems to roughly work.
> 

Could you make a pull request? We don't have any windows users to make this change.
