### ISSUE TITLE
Indexer restarting over and over on down and up in dev

### ISSUE THREAD

**Issue by bbroder-algo** [algorand/sandbox#163]
### Subject of the issue

Indexer can't restart itself properly if brought down before a single transaction has been made.

### Your environment

Sandbox from master
Docker on macos m1

### Steps to reproduce

1.  Install docker desktop on an M1 macos
2.  Install the sandbox from master (980a3)
3.  Run ./sandbox clean && ./sandbox up dev -v && ./sandbox down && ./sandbox up -v

### Expected behaviour
The sandbox is built, started, stopped, then starts again. 

### Actual behaviour
The indexer gets stuck in a restart loop when brought back up, with the error in MakeProcessorWithLedger(), err: addGenesisBlock() handler err: AddBlock() err: TxWithRetry() err: attemptTx() err: AddBlock() adding block round 0 but next round to account is 1. 

![Capture](https://user-images.githubusercontent.com/118225939/207973212-009bb152-44f0-4bdf-902b-05e01c622ed6.PNG)

**Comment by theosth** [comment]
For me this Error only occurs when the dev Sandbox ist stopped before the first Round of the dev-chain is started.
-> I guess this is because the genesis Block is then missing in the Indexer.
If you send any txn after starting the sandbox, (? thereby adding the genesis Block in the Indexer ?) this does't occur.
Hope this is helpful.

**Comment by robdmoore** [comment]
Is there an eta on a fix for this one?

**Comment by winder** [comment]
A release that solves this problem will be available soon.

**Comment by bbroder-algo** [comment]
thank you!
